import argparse
import json
import os
from typing import Any, Dict, Optional, Set
import pandas as pd
from datasets import load_dataset, Dataset
import random

"""Utility functions for loading and processing datasets."""

SYSTEM_MESSAGE_GENERIC = "You are an expert Python programmer. You will be given a question (problem specification) and will generate a correct Python program that matches the specification and passes all tests."

# Pre-computed KodCode indices to exclude.  Generated by scanning all test
# code for (a) dangerous constructs (threading, subprocess, sockets, …) that
# hang the evaluation subprocess, and (b) self-contained pytest-style tests
# whose ``def test_*`` functions pass even with an empty solution module.
# See ``kodcode_excluded_indices.json`` for details.
_EXCLUDED_KODCODE_INDICES: Optional[Set[int]] = None


def _load_excluded_indices() -> Set[int]:
    global _EXCLUDED_KODCODE_INDICES
    if _EXCLUDED_KODCODE_INDICES is None:
        path = os.path.join(os.path.dirname(__file__), "kodcode_excluded_indices.json")
        with open(path) as f:
            _EXCLUDED_KODCODE_INDICES = set(json.load(f)["excluded_indices"])
        print(f"Loaded {len(_EXCLUDED_KODCODE_INDICES)} excluded KodCode indices from {path}")
    return _EXCLUDED_KODCODE_INDICES


KODCODE_FORMATTING_MESSAGE_WITH_FUNCTION_DECLARATION = """Please solve the programming task below in Python.
{question}

Note that the function declaration is {function_declaration}. Your code should be wrapped in a markdown code block"""

KODCODE_FORMATTING_MESSAGE_WITH_FUNCTION_DECLARATIONS = """Please solve the programming task below in Python.

{question}

Note that the functions you need to implement have the following declarations:
{function_declarations}.

Your code should be wrapped in a markdown code block"""

KODCODE_FORMATTING_MESSAGE_WITHOUT_FUNCTION_DECLARATION = """Please solve the programming task below in Python.
{question}"""


def process_eurus_code_example(example: Dict[str, Any], idx: int, dataset_name: str, split: str) -> Optional[Dict[str, Any]]:
    """Process a single dataset example.

    Args:
        example: Raw dataset example
        idx: Index of the example
        dataset_name: Name of the dataset
        split: Dataset split ('train' or 'test')

    Returns:
        Processed example dictionary or None if processing fails
    """
    question = example["prompt"][-1]["content"]
    tests = json.loads(example["reward_model"]["ground_truth"])

    assert isinstance(tests, dict), f"Expected tests to be a dict, got {type(tests)}: {tests}"
    assert "inputs" in tests and "outputs" in tests
    assert isinstance(tests["inputs"], list) and isinstance(tests["outputs"], list)
    assert len(tests["inputs"]) == len(tests["outputs"])

    tests = json.dumps(tests)

    data = {
        "data_source": dataset_name,
        "prompt": [
            {
                "role": "system",
                "content": SYSTEM_MESSAGE_GENERIC
            },
            {
                "role": "user",
                "content": question
            }
        ],
        "ability": "code",
        "env_class": "mix_code",
        "reward_spec": {"method": "inputs", "ground_truth": tests},
        "extra_info": {
            "split": split,
            "index": idx
        },
    }
    return data

def process_kodcode_example(example: Dict[str, Any], idx: int, dataset_name: str, split: str) -> Optional[Dict[str, Any]]:
    """Process a single dataset example.

    Args:
        example: Raw dataset example
        idx: Index of the example
        dataset_name: Name of the dataset
        split: Dataset split ('train' or 'test')

    Returns:
        Processed example dictionary or None if processing fails
    """
    # Filter out dangerous and self-contained tests
    excluded = _load_excluded_indices()
    if idx in excluded:
        return None

    question = example["question"]
    test = example["test"]
    test_info = example["test_info"]
    if len(test_info) > 1:
        # figure out which function declarations are present in test
        condensed_test_info = []
        for info in test_info:
            assert "function_declaration" in info, f"Expected 'function_declaration' in test_info, got {test_info}"
            function_name = info["function_name"]
            assert function_name in info["function_declaration"], f"Expected function name {function_name} in function declaration {info['function_declaration']}"
            if function_name + "(" in test:
                condensed_test_info.append(info)
        test_info = condensed_test_info
    if len(test_info) == 1:
        assert "function_declaration" in test_info[0], f"Expected 'function_declaration' in test_info, got {test_info}"
        function_declaration = test_info[0]["function_declaration"]
        prompt = KODCODE_FORMATTING_MESSAGE_WITH_FUNCTION_DECLARATION.format(question=question, function_declaration=function_declaration)
    elif len(test_info) > 1:
        function_declarations = "\n".join([info["function_declaration"] for info in test_info])
        prompt = KODCODE_FORMATTING_MESSAGE_WITH_FUNCTION_DECLARATIONS.format(question=question, function_declarations=function_declarations)
    else:
        prompt = KODCODE_FORMATTING_MESSAGE_WITHOUT_FUNCTION_DECLARATION.format(question=question)

    assert isinstance(test, str)

    data = {
        "data_source": dataset_name,
        "prompt": [
            {
                "role": "system",
                "content": SYSTEM_MESSAGE_GENERIC
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        "env_class": "mix_code",
        "ability": "code",
        "reward_spec": {"method": "assertions", "ground_truth": test},
        "extra_info": {
            "split": split,
            "index": idx
        },
    }
    return data


def process_eurus_code_data():
    """Process a dataset for Eurus 2 RL data code split.
    """
    # Load dataset
    raw_data = load_dataset("PRIME-RL/Eurus-2-RL-Data")["train"]

    # filter for ability = code
    raw_data = raw_data.filter(lambda x: x["ability"] == "code")

    # Process examples
    processed_data = []
    for idx, example in enumerate(raw_data):
        processed_example = process_eurus_code_example(example, idx, "eurus", "train")
        processed_data.append(processed_example)

    return processed_data

def process_kodcode_data():
    """Process a dataset for KodCode.

    Filters out examples with dangerous test constructs (threading, subprocess,
    sockets) and self-contained tests that don't actually validate model code,
    using pre-computed indices from kodcode_excluded_indices.json.
    """
    # Load dataset
    raw_data = load_dataset("KodCode/KodCode-V1")["train"]

    # Process examples
    processed_data = []
    filtered = 0
    for idx, example in enumerate(raw_data):
        processed_example = process_kodcode_example(example, idx, "kodcode", "train")
        if processed_example is not None:
            processed_data.append(processed_example)
        else:
            filtered += 1

    print(f"KodCode: kept {len(processed_data)}, filtered {filtered} "
          f"(dangerous or self-contained tests)")
    return processed_data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Process datasets for code training")
    parser.add_argument("--output_dir", default="/root/data/eurus")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for shuffling the dataset")
    args = parser.parse_args()

    local_dir = args.output_dir
    print(f"Local_dir:{local_dir}")

    # Make local directory if it doesn't exist
    if not os.path.exists(local_dir):
        os.makedirs(local_dir, exist_ok=True)

    # Process train dataset
    eurus_code_data = process_eurus_code_data()
    kodcode_data = process_kodcode_data()

    # print a few examples for sanity check
    print("Sample Eurus code example:")
    print(json.dumps(eurus_code_data[0], indent=2))
    print("\nSample KodCode example:")
    print(json.dumps(kodcode_data[0], indent=2))

    # merge and shuffle the datasets
    train_data = eurus_code_data + kodcode_data
    random.seed(args.seed)
    random.shuffle(train_data)

    # subset for validation
    validation_data = train_data[:1000]
    train_data = train_data[1000:]
    
    train_data = Dataset.from_list(train_data)
    validation_data = Dataset.from_list(validation_data)

    # Save combined train dataset
    train_data_df = pd.DataFrame(train_data)
    train_data_df.to_parquet(os.path.join(local_dir, "train_data.parquet"), index=False)
    print(f"Saved combined train dataset with {len(train_data)} examples to {os.path.join(local_dir, 'train_data.parquet')}")
    # Save validation dataset
    validation_data_df = pd.DataFrame(validation_data)
    validation_data_df.to_parquet(os.path.join(local_dir, "validation_data.parquet"), index=False)
    print(f"Saved validation dataset with {len(validation_data)} examples to {os.path.join(local_dir, 'validation_data.parquet')}")
